"""Reproducible simulator-only OPE benchmark for stay and IQL policies.

Output: outputs/policy_evaluation_report.md
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import torch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


def _evaluate(
    data: dict[str, np.ndarray],
    *,
    policy: str,
    target_probs: np.ndarray,
    q_values: np.ndarray,
    state_values: np.ndarray,
    next_state_values: np.ndarray,
    seed: int,
) -> dict:
    from src.rl.offline.evaluation import (
        ope_doubly_robust,
        ope_fqe,
        ope_weighted_importance_sampling,
    )

    fqe = ope_fqe(
        data["states"],
        data["actions"],
        data["rewards"],
        data["next_states"],
        data["dones"],
        epochs=50,
        seed=seed,
    )
    wis, wis_low, wis_high = ope_weighted_importance_sampling(
        data["rewards"],
        data["dones"],
        data["behavior_probs"],
        target_probs=target_probs,
        trajectory_ids=data["trajectory_ids"],
        seed=seed,
    )
    dr = ope_doubly_robust(
        data["states"],
        data["actions"],
        data["rewards"],
        data["next_states"],
        data["dones"],
        trajectory_ids=data["trajectory_ids"],
        behavior_probs=data["behavior_probs"],
        target_probs=target_probs,
        q_values=q_values,
        state_values=state_values,
        next_state_values=next_state_values,
        seed=seed,
    )
    return {
        "policy": policy,
        "fqe_diagnostic": fqe,
        "wis_estimate": wis,
        "wis_ci95_low": wis_low,
        "wis_ci95_high": wis_high,
        "dr_estimate": dr.dr_estimate,
        "dr_ci95_low": dr.ci95_low,
        "dr_ci95_high": dr.ci95_high,
        "mean_reward": float(data["rewards"].mean()),
        "n_transitions": len(data["rewards"]),
        "n_trajectories": dr.n_trajectories,
    }


def _run_stay_evaluation(*, drivers: int = 10, seed: int = 42) -> dict:
    """Evaluate the deterministic stay policy on data generated by that policy."""
    from src.rl.offline import OfflineBuffer
    from src.simulator.v2 import DynamicSimulator
    from src.simulator.v2.engine import SimulatorConfig

    buffer = OfflineBuffer(capacity=50_000, state_dim=7, seed=seed)
    simulator = DynamicSimulator(SimulatorConfig(driver_count=drivers, seed=seed))

    def stay_policy(_time, location, _state):
        return location, 1.0

    buffer.collect_trajectories_from_v2(simulator, episodes=5, strategy=stay_policy)
    data = buffer.as_ordered_dict()
    zeros = np.zeros(buffer.size, dtype=np.float32)
    return _evaluate(
        data,
        policy="Stay (on-policy baseline)",
        target_probs=np.ones(buffer.size, dtype=np.float32),
        q_values=zeros,
        state_values=zeros,
        next_state_values=zeros,
        seed=seed,
    )


def _run_iql_evaluation(*, drivers: int = 10, seed: int = 42) -> dict:
    """Evaluate a deterministic IQL policy on uniform-exploration trajectories."""
    from src.rl.offline import IQLAgent, OfflineBuffer
    from src.rl.offline.iql import train_iql
    from src.simulator.v2 import DynamicSimulator
    from src.simulator.v2.engine import SimulatorConfig

    state_dim = 7
    action_dim = 263
    rng = np.random.default_rng(seed)
    torch.manual_seed(seed)
    buffer = OfflineBuffer(capacity=50_000, state_dim=state_dim, seed=seed)
    simulator = DynamicSimulator(SimulatorConfig(driver_count=drivers, seed=seed))

    def exploration_policy(_time, _location, _state):
        return int(rng.integers(1, action_dim + 1)), 1.0 / action_dim

    buffer.collect_trajectories_from_v2(simulator, episodes=5, strategy=exploration_policy)
    agent = IQLAgent(state_dim=state_dim, action_dim=action_dim, device="cpu")
    train_iql(agent, buffer, steps=300, log_interval=100)
    data = buffer.as_ordered_dict()

    states = torch.as_tensor(data["states"], dtype=torch.float32)
    next_states = torch.as_tensor(data["next_states"], dtype=torch.float32)
    logged_actions = torch.as_tensor(data["actions"], dtype=torch.float32).unsqueeze(-1)
    with torch.no_grad():
        q_values = agent.get_q_values(states, logged_actions).cpu().numpy().ravel()
        state_values = agent.get_value(states).cpu().numpy().ravel()
        next_state_values = agent.get_value(next_states).cpu().numpy().ravel()

    candidates = np.arange(1, action_dim + 1)
    selected_actions = np.array(
        [candidates[np.argmax(agent.score_actions(state, candidates))] for state in data["states"]]
    )
    target_probs = (selected_actions == data["actions"]).astype(np.float32)
    return _evaluate(
        data,
        policy="IQL (uniform-exploration behavior)",
        target_probs=target_probs,
        q_values=q_values,
        state_values=state_values,
        next_state_values=next_state_values,
        seed=seed,
    )


def _generate_report(results: list[dict], *, seed: int) -> str:
    """Generate an auditable Markdown report from OPE results."""
    lines = [
        "# Offline Policy Evaluation Report",
        "",
        f"**Seed:** {seed}",
        "",
        "## Scope",
        "",
        "This is a reproducible **simulator-only methodological benchmark**. It is not "
        "real-world causal evidence: TLC trip records do not contain logged recommendations, "
        "driver acceptance, or behavior-policy propensities.",
        "",
        "FQE below is a logged-action diagnostic. WIS and sequential DR use complete driver "
        "trajectories, explicit target/behavior probabilities, and trajectory bootstrap intervals.",
        "",
        "## Results",
        "",
        "| Policy | Method | Estimate | 95% CI Low | 95% CI High |",
        "|--------|--------|---------:|-----------:|------------:|",
    ]
    for result in results:
        policy = result["policy"]
        lines.append(f"| {policy} | FQE diagnostic | {result['fqe_diagnostic']:.4f} | - | - |")
        lines.append(
            f"| {policy} | WIS | {result['wis_estimate']:.4f} | "
            f"{result['wis_ci95_low']:.4f} | {result['wis_ci95_high']:.4f} |"
        )
        lines.append(
            f"| {policy} | Sequential DR | {result['dr_estimate']:.4f} | "
            f"{result['dr_ci95_low']:.4f} | {result['dr_ci95_high']:.4f} |"
        )
        lines.append(f"| {policy} | Mean transition reward | {result['mean_reward']:.4f} | - | - |")
        lines.append(
            f"| {policy} | Data volume | {result['n_transitions']} transitions / "
            f"{result['n_trajectories']} trajectories | - | - |"
        )

    lines.extend(
        [
            "",
            "## Policy and estimator details",
            "",
            "- Stay data use a deterministic stay behavior policy and evaluate that same policy "
            "with probability 1.",
            "- IQL data use uniform random behavior over 263 zones with logged probability 1/263; "
            "the evaluated IQL policy is deterministic, so its logged-action probability is 0 or 1.",
            "- IQL Q/V nuisance predictions come from the trained IQL networks. The stay DR "
            "benchmark uses zero nuisance predictions and therefore reduces to an importance-weighted return.",
            "- Confidence intervals resample complete driver trajectories (100 bootstrap draws).",
            "- Importance weighting can be unstable when the deterministic IQL policy has little "
            "overlap with uniform behavior data; intervals do not repair a lack of support.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--drivers", type=int, default=10)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--output", type=Path, default=ROOT / "outputs/policy_evaluation_report.md")
    args = parser.parse_args()

    results = [
        _run_stay_evaluation(drivers=args.drivers, seed=args.seed),
        _run_iql_evaluation(drivers=args.drivers, seed=args.seed),
    ]
    report = _generate_report(results, seed=args.seed)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")
    print(f"Report written to {args.output}")


if __name__ == "__main__":
    main()
